### PR TITLE
Misc bug fixes

### LINKED ISSUE #135: Bugfix - modal opens when using image carousel

### PR DESCRIPTION
**Pull request by jplimmer**
A few small bug/styling fixes - I'm sure there are more out there...

### What changed
- ImageCarousel buttons no longer open modal window.
- Fixed lowerCase issue with product categories nav, so it now filters correctly.
    - also renamed keys to "category" and "page", because I'm picky 👀 😇 
- Hero text is centered at mobile screen size, and images have 'object-cover' (mainly for the larger image).
- Current page is underlined in Pagination.
- Wrapped ProductDetail in suspense with skeleton (should fix issue with white loading space to the right).
- Added working AddToCart button to ProductDetail (although doesn't link with quantity selector).
- Removed misaligned basket content from nav bar.
- Fixed scroll behaviour of Hero images with modal.
- CategorySelect check marks now update on client-side navigation (e.g. from Products section in nav bar).

Closes #135

### CODE REVIEW

File: src/components/navigation/basket-nav-item.tsx [hunk 1]
```diff
@@ -25,15 +22,15 @@ export function BasketNavItem({
         )}
         <span className="sr-only">Basket ({cartCount} items)</span>
       </NavigationMenuTrigger>
-      <NavigationMenuContent>
+      {/* <NavigationMenuContent>
```
Comment (Tob-private) [inline src/components/navigation/basket-nav-item.tsx:25]: why comment this out?

File: src/components/products/product-detail.tsx [hunk 2]
```diff
@@ -1,12 +1,22 @@
...
 
-export default function ProductDetail({ product }: { product: Product }) {
+export default async function ProductDetail({
+  productPromise,
+}: {
+  productPromise: Promise<Product | null>;
+}) {
+  const product = await productPromise;
+
+  console.log(product);
```
Comment (Tob-private) [inline src/components/products/product-detail.tsx]: delete

File: src/components/products/product-image-carousel.tsx [hunk 3]
```diff
@@ -78,14 +78,20 @@ export default function ProductImageCarousel({
       {validImages.length > 1 && (
         <>
           <button
-            onClick={prevSlide}
+            onClick={(e: React.MouseEvent) => {
+              e.preventDefault();
+              prevSlide();
+            }}
```
Comment (Tob-private) [inline src/components/products/product-image-carousel.tsx]: could these be made into a carousel function, where you input the function you want the button to exec on click. Makes the button look cleaner

**Review by Tob-private — CHANGES_REQUESTED** [review]
some small things

File: src/components/products/product-detail.tsx (hunk 2 above)
Comment (Tob-private) [reply src/components/products/product-detail.tsx]: hahah you got this one already

File: src/components/navigation/basket-nav-item.tsx (hunk 1 above)
Comment (jplimmer) [reply src/components/navigation/basket-nav-item.tsx:25]: At the moment, due to quirks with the NavigationMenu component, it shows up off to the left (under search). Given it doens't really add anything yet, thought it made sense to just comment out (and could be fixed properly in the future)

File: src/components/products/product-image-carousel.tsx (hunk 3 above)
Comment (jplimmer) [reply src/components/products/product-image-carousel.tsx]: Something like this?

image

Comment (Tob-private) [reply src/components/products/product-image-carousel.tsx]: exaclty like that!

**Review by Tob-private — DISMISSED** [review]

**Comment by jplimmer** [comment]
Found two more small ones while approval still pending!

**Review by Tob-private — APPROVED** [review]

**Review by Sain49 — APPROVED** [review]
Snyggt!
